collections:
  - name: "products"
    label: "Productos"
    folder: "src/content/products"
    create: true

    extension: "md"
    format: "frontmatter"
    identifier_field: "name"

    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Ej: argentina-picada" }
      - { label: "Precio", name: "price", widget: "number", value_type: "int", min: 0 }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Descripci√≥n", name: "description", widget: "text" }
      - { label: "Orden", name: "order", widget: "number", value_type: "int", default: 0, required: false }
      - { label: "Activo", name: "active", widget: "boolean", default: true, required: false }
